apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: simple-trade
  labels:
    app: redis
    app.kubernetes.io/part-of: simple-trade
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  type: ClusterIP
