apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: simple-trade
  labels:
    app: order-service
    app.kubernetes.io/part-of: simple-trade
spec:
  selector:
    app: order-service
  ports:
    - port: 50053
      targetPort: 50053
      name: grpc
  type: ClusterIP
