apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: simple-trade
  labels:
    app: postgres
    app.kubernetes.io/part-of: simple-trade
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/simple-trade/postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: simple-trade
  labels:
    app: postgres
    app.kubernetes.io/part-of: simple-trade
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
