apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: simple-trade
  labels:
    app: postgres
    app.kubernetes.io/part-of: simple-trade
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  type: ClusterIP
