# Dev 环境Overlay
# 基础设施指向本地 Docker Compose 服务
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: simple-trade
resources:
  - ../../base
patches:
  - path: external-services-patch.yaml
    target:
      kind: Service
      name: postgres
  - path: external-services-patch.yaml
    target:
      kind: Service
      name: redis
  - path: external-services-patch.yaml
    target:
      kind: Service
      name: kafka
  - path: external-services-patch.yaml
    target:
      kind: Service
      name: nacos
  - path: config-patch.yaml
  - path: secrets-patch.yaml
